#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f MasterCPU.vcd

# run Verilator to translate Veriliog to C++, including C++ testbench

verilator -Wall --cc ../rtl/alu.sv
verilator -Wall --cc ../rtl/reg_file.sv
verilator -Wall --cc ../rtl/data_mem.sv
verilator -Wall --cc ../rtl/orange.sv 

verilator -Wall --cc ../rtl/P_C.sv

verilator -Wall --cc ../rtl/control.sv
verilator -Wall --cc ../rtl/sextend.sv
verilator -Wall --cc ../rtl/instmem.sv
verilator -Wall --cc ../rtl/green.sv

verilator -Wall --cc --trace ../rtl/master.sv --exe cpu_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir -f Vmaster.mk Vmaster

#run executable simulation file
obj_dir/Vmaster
