#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f VP_C.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace -I../ ../../rtl/P_C.sv --exe PC_testbench.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VP_C.mk VP_C

# run executable simulation file
obj_dir/VP_C
